#ifndef PROJECT_BRUTEFORCER_BRUTEFORCERCONFIG_HPP_
#define PROJECT_BRUTEFORCER_BRUTEFORCERCONFIG_HPP_

#include <cstddef>

const size_t PASSWORD_SIZE = 8;
const size_t NUMBERS_COUNT = 10;
const size_t VARIANTS_COUNT = 100000000;

#endif  // PROJECT_BRUTEFORCER_BRUTEFORCERCONFIG_HPP_